import math

# Output configuration
filename = "simulated_can_acceleration.txt"
duration_ms = 5000

# Boundary conditions
rpm_start, rpm_end = 1200, 2700
speed_start, speed_end = 20, 60
temp_start, temp_end = 0x7A, 0x80 # 5% variance

def generate_can_trace():
    with open(filename, "w") as f:
        # Write PCAN Header
        f.write(";$FILEVERSION=1.1\n")
        f.write(";$STARTTIME=46190.6957282176\n;\n")
        f.write(";   Generated by AI Simulation\n;\n")
        f.write(";   Message Number\n")
        f.write(";   |         Time Offset (ms)\n")
        f.write(";   |         |        Type\n")
        f.write(";   |         |        |        ID (hex)\n")
        f.write(";   |         |        |        |     Data Length\n")
        f.write(";   |         |        |        |     |   Data Bytes (hex) ...\n")
        f.write(";   |         |        |        |     |   |\n")
        f.write(";---+--   ----+----  --+--  ----+---  +  -+ -- -- -- -- -- -- --\n")

        msg_count = 1
        
        # We will loop in 10ms intervals as per the original trace
        for time_ms in range(0, duration_ms + 10, 10):
            progress = time_ms / duration_ms
            
            # 1. RPM Calculation (ID 0106)
            current_rpm = rpm_start + (rpm_end - rpm_start) * progress
            rpm_can_val = int(current_rpm * 4)
            rpm_byte0 = (rpm_can_val >> 8) & 0xFF
            rpm_byte1 = rpm_can_val & 0xFF
            f.write(f" {msg_count:>5})    {time_ms:>8.1f}  Rx         0106  8  {rpm_byte0:02X} {rpm_byte1:02X} 00 00 00 00 00 00\n")
            msg_count += 1
            
            # 2. Speed Calculation (ID 0197)
            current_speed = int(speed_start + (speed_end - speed_start) * progress)
            f.write(f" {msg_count:>5})    {time_ms:>8.1f}  Rx         0197  8  {current_speed:02X} 00 00 00 00 00 00 00\n")
            msg_count += 1
            
            # 3. Temp Calculation (ID 0280) - Transmitted roughly every 100ms
            if time_ms % 100 == 0:
                current_temp = int(temp_start + (temp_end - temp_start) * progress)
                f.write(f" {msg_count:>5})    {time_ms:>8.1f}  Rx         0280  8  00 00 {current_temp:02X} 50 00 00 00 00\n")
                msg_count += 1
                
                # Gear Calculation (ID 02B5) - Also every 100ms (Hardcoded to 2nd Gear '02')
                f.write(f" {msg_count:>5})    {time_ms:>8.1f}  Rx         02B5  8  00 00 02 00 00 00 00 00\n")
                msg_count += 1

generate_can_trace()
print(f"Generated {filename} successfully.")